name: BLA BLA BLA BLA

on:
  push:
    branches:
      - master
      - feature/logs

#какие задачи нужно сделать,для этого нужна jobs
jobs:
  # Название задачи, то есть место где находяться задачи
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Test
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: test_in_use
        run: python test.py
      
      - name: docker login password
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker image
        run: docker build -t bla001 .


      - name: docker push
        run: |
          docker tag bla001 tachyonk/boom:latest
          docker tag bla001 tachyonk/boom:${{ github.sha }}
          docker push tachyonk/boom:latest
          docker push tachyonk/boom:${{ github.sha }}
      - name: ssh connect
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            sudo dnf update -y
            sudo dnf install docker -y
            sudo docker stop $(sudo docker ps -aq) || true
            sudo docker rm $(sudo docker ps -aq) || true
            sudo docker rmi $(sudo docker images -q) -f || true
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            
            sudo docker pull tachyonk/boom:latest
            
            sudo docker run -d -p 80:80 tachyonk/boom:latest
